(ns mini-registradora.db)

(def default-db
  {:nome "registradora"
   :tipo-tela ""
   :tela-consulta ""
   :consulta {:swap {} :cdb {} :participante {}}
   :cadastro {:swap {} :cdb {} :participante {}}
   :mocke {:participante {:status "pendente",
                          :cnpj "12345678904330",
                          :tipo_de_instituicao "Instituição A",
                          :setor_area "Setor Y",
                          :razao_social "Empresa ABC",
                          :nome_fantasia "ABC Ltda",
                          :codigo_agregador "789",
                          :controle_acionario "Controle A",
                          :origem_do_capital "Origem B",
                          :isencao_inscr_estadual "Sim",
                          :num_inscr_estadual "12345",
                          :isencao_inscr_municipal "Sim",
                          :num_inscr_municipal "54321",
                          :grupo_economico "Grupo Z",
                          :email "empresa.abc@example.com",
                          :telefone "888888888",
                          :ramal "456",
                          :logradouro "Rua Principal",
                          :numero "123",
                          :complemento "Apto 4",
                          :bairro "Centro",
                          :municipio "Cidade A",
                          :cep "12345-678",
                          :uf "UF A",
                          :pais "País A",
                          :data_criacao "2023-06-30",
                          :data_atualizacao "2023-06-30"}
           :cdb {:id_participante "123456",
                 :tipo_regime "Regime X",
                 :conta_cpf_cnpj "12345678901",
                 :data_emissao "2023-06-30",
                 :data_vencimento "2023-12-31",
                 :valor_unitario_emissao 100.50,
                 :codigo_isin "ABC123",
                 :local_emissao "Local A",
                 :municipio_emissao "Município A",
                 :uf_local_emissao "UF A",
                 :local_pagamento "Local P",
                 :municipio_pagamento "Município P",
                 :uf_local_pagamento "UF P",
                 :cond_resgate_antecipado "Sim",
                 :vinculado true,
                 :forma_pagamento "Forma A",
                 :multiplas_curvas "Sim",
                 :rentabilidade_ind_tx_flut "Rentabilidade X",
                 :taxa_flutuante 0.5,
                 :taxa_juros_spread 0.2,
                 :status "pendente"}
           :swap {:status "pendente",
                  :id_participante "456123",
                  :tipo "Tipo A",
                  :tipo_pagamento "Pagamento A",
                  :cnpj_comprador "12345678901234",
                  :cnpj_vendedor "56789012345678",
                  :data_inicio "2023-06-30",
                  :data_vencimento "2023-12-31",
                  :valor_base 1000.00,
                  :adesao_contrato "Adesão X",
                  :percentual_comprador 0.8,
                  :categoria_comprador "Categoria X",
                  :juros_comprador 0.1,
                  :curva_comprador "Curva X",
                  :percentual_vendedor 0.2,
                  :categoria_vendedor "Categoria Z",
                  :juros_vendedor 0.05,
                  :curva_vendedor "Curva Y",
                  :caracteristicas_contrato "Características A"}}})
